default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 1
  host: localhost

development:
  <<: *default
  database: development_stackoverflow

test:
  <<: *default
  database: test_stackoverflow

# production:
#   <<: *default
#   database: production_stackoverflow
