# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4665e7dacda20b70c593a1644d3a730b450c21f05e3c09deac069beb926fe5b0426a0e332ef6fbc9251ecffd3b95dabac9312f7803bf96c7ac9e842b767b2fa6

test:
  secret_key_base: 40a49e4047ff29734cb48f654d8d6e71c3266e819f5340ca054691450e259f1dee4eeaf95c487ce38b9a25c71d18485d198b8719ca14160b1afdd5c0f7c22b9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
